version: '3.5'

services:
  postgres-auth:
    container_name: postgres-auth-container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres-auth
    volumes:
      - postgres-auth:/data/postgres-auth
    ports:
      - "5432:5432"
    networks:
      - postgres-auth
    restart: unless-stopped

networks:
  postgres-auth:
    driver: bridge

volumes:
  postgres-auth: